Repository kubeflow/community, pull requests merged in 2018-03, with the labels that each got.

#25 Create an initial OWNERS file.
  OWNERS
Labels: size/S

#27 Provide instructions on the PR workflow based on OWNERS files.
  contributing.md
Labels: approved, lgtm, size/L

#36 Revised and simplified info for hosting a community meeting
  OWNERS
  README.md
  how-to/community_meetings.md
Labels: lgtm, size/L

#37 Master list of project-wide issue labels
  issue-labels.md
Labels: approved, lgtm, size/M

#38 Add starter links to contributor guide
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/M

#39 Modify OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#30 Add tf-operator design doc for API v1alpha2
  proposals/tf-operator-design-v1alpha2.md
Labels: approved, lgtm, size/L

#40 Replace starter label with good first issue
  issue-labels.md
Labels: approved, lgtm, size/XS

#33 Pytorch operator proposal
  proposals/diagrams/all-reduce-pytorch-operator.jpeg
  proposals/pytorch-operator-proposal.md
Labels: approved, do-not-merge/hold, lgtm, size/L

#42 Add tf-operator v1alpha2 design proposal into accepted-proposals
  accepted-proposals.md
Labels: approved, lgtm, size/XS

#45 Add repository setup instructions
  repository-setup.md
Labels: approved, lgtm, size/M
