Repository kubeflow/community, pull requests merged in 2018-12, with the labels that each got.

#215 Added gyliu513 as a member.
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#217 Add xieydd and pineking as member
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, ok-to-test, size/S

#212 Add suensummit to members.yaml.
  members.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#103 add yuvipanda to jupyter org and members list
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, size/XS

#221 Adding gabrielwen to community member list
  members.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS
