Repository kubeflow/community, pull requests merged in 2018-11, with the labels that each got.

#202 Add jwwandy to member.yaml
  members.yaml
Labels: approved, lgtm, size/XS

#203 Add an inclusivity guide
  INCLUSIVITY.md
Labels: approved, lgtm, size/L

#207 Added netankit to members.yaml
  members.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#209 Added jpza to members.yaml
  members.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#206 Add stevencasey to members.yaml
  members.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#208 A script to compute PRs by company.
  scripts/prs_by_company.py
Labels: approved, lgtm, size/L

#211 Remove Jose from Intel, add Kam and Ebi to Intel
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, size/S

#210 Add myself and shopify to members
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, size/S

#214 add hougangliu as kubeflow member
  members.yaml
Labels: approved, lgtm, ok-to-test, size/XS
