Repository kubeflow/community, pull requests merged in 2018-05, with the labels that each got.

#130 Enable https for grafana and deploy at devstats.kubeflow.org
  devstats/ks-app/.ksonnet/registries/kubeflow/e2c2c7c49e578472ba57f91f3b2a5f4d1a2d0289.yaml
  devstats/ks-app/app.yaml
  devstats/ks-app/components/cert-manager.jsonnet
  devstats/ks-app/components/certmanager.jsonnet
  devstats/ks-app/components/devstats-parts.libsonnet
  devstats/ks-app/components/devstats.jsonnet
  devstats/ks-app/components/params.libsonnet
  devstats/ks-app/vendor/kubeflow/core/README.md
  devstats/ks-app/vendor/kubeflow/core/all.libsonnet
  devstats/ks-app/vendor/kubeflow/core/ambassador.libsonnet
  devstats/ks-app/vendor/kubeflow/core/centraldashboard.libsonnet
  devstats/ks-app/vendor/kubeflow/core/cert-manager.libsonnet
  devstats/ks-app/vendor/kubeflow/core/cloud-endpoints.libsonnet
  devstats/ks-app/vendor/kubeflow/core/iap.libsonnet
  devstats/ks-app/vendor/kubeflow/core/jupyterhub.libsonnet
  devstats/ks-app/vendor/kubeflow/core/kubeform_spawner.py
  devstats/ks-app/vendor/kubeflow/core/nfs.libsonnet
  devstats/ks-app/vendor/kubeflow/core/parts.yaml
  devstats/ks-app/vendor/kubeflow/core/prototypes/all.jsonnet
  devstats/ks-app/vendor/kubeflow/core/prototypes/cert-manager.jsonnet
  devstats/ks-app/vendor/kubeflow/core/prototypes/cloud-endpoints.jsonnet
  devstats/ks-app/vendor/kubeflow/core/prototypes/iap-ingress.jsonnet
  devstats/ks-app/vendor/kubeflow/core/prototypes/tensorboard.jsonnet
  devstats/ks-app/vendor/kubeflow/core/spartakus.libsonnet
  devstats/ks-app/vendor/kubeflow/core/tensorboard.libsonnet
  devstats/ks-app/vendor/kubeflow/core/tests/ambassador_test.jsonnet
  devstats/ks-app/vendor/kubeflow/core/tests/iap_test.jsonnet
  devstats/ks-app/vendor/kubeflow/core/tests/jupyterhub_test.jsonnet
  devstats/ks-app/vendor/kubeflow/core/tests/nfs_test.jsonnet
  devstats/ks-app/vendor/kubeflow/core/tests/spartakus_test.jsonnet
  devstats/ks-app/vendor/kubeflow/core/tests/tf-job_test.jsonnet
  devstats/ks-app/vendor/kubeflow/core/tests/util_test.jsonnet
  devstats/ks-app/vendor/kubeflow/core/tf-job.libsonnet
  devstats/ks-app/vendor/kubeflow/core/util.libsonnet
  devstats/ks-app/vendor/kubeflow/core/version-info.json
  devstats/ks-app/vendor/kubeflow/core/version.libsonnet
Labels: approved, lgtm, size/XXL

#134 Added abhi-g as a new member
  members.yaml
Labels: approved, lgtm, size/XS

#139 Add MPI Operator proposal.
  proposals/diagrams/mpi-operator.png
  proposals/mpi-operator-proposal.md
Labels: approved, lgtm, size/L

#140 Minor edits to address review comments for the MPI Operator proposal.
  proposals/mpi-operator-proposal.md
Labels: approved, lgtm, size/S

#141 Add link to allreduce introduction.
  proposals/mpi-operator-proposal.md
Labels: approved, lgtm, size/XS

#142 Add rongou to members
  members.yaml
Labels: approved, lgtm, size/XS

#145 Add chainer-operator proposal.
  proposals/chainer-operator-proposal.md
Labels: approved, lgtm, size/L

#146 Removing elsonrodirguez from Intel
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, size/XS
