Repository kubeflow/community, pull requests merged in 2018-10, with the labels that each got.

#197 Create a script to compute stats about number of issues in each area.
  .gitignore
  how-to/release_tracking.md
  scripts/get_issue_counts.py
  scripts/get_issue_counts_test.py
Labels: approved, lgtm, size/L

#196 Add Primer & alphabetize
  member_organizations.yaml
Labels: approved, lgtm, size/M

#198 Add mrick to members.yaml
  members.yaml
Labels: approved, lgtm, size/XS

#199 Add bharaththiruveedula to members.yaml
  members.yaml
Labels: approved, lgtm, size/XS

#193 Add yangpa as Kubeflow member
  members.yaml
Labels: approved, lgtm, size/XS
