Repository kubeflow/community, pull requests merged in 2018-04, with the labels that each got.

#41 [WIP] Caffe2 operator proposal
  proposals/caffe2-operator-proposal.md
Labels: approved, lgtm, size/L, status/in progress

#58 Start a directory to keep track of contact information for members
  members.yaml
Labels: approved, lgtm, size/S

#59 Update community meeting process to not rely on Zoom hosting the recording
  how-to/community_meetings.md
Labels: approved, lgtm, size/S

#63 Create a list of companies/organizations contributing to Kubeflow
  CONTRIBUTING.md
  member_organizations.yaml
Labels: approved, lgtm, size/M

#64 update member_organizations.yaml
  member_organizations.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#72 add kam to members list
  members.yaml
Labels: approved, lgtm, size/XS

#70 Add Red Hat to member organizations
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#71 add willb to members
  members.yaml
Labels: approved, lgtm, size/XS

#68 members: Add @gaocegege
  members.yaml
Labels: approved, lgtm, size/XS

#65 Update member_organizations.yaml
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#74 add members from Caicloud
  member_organizations.yaml
Labels: approved, lgtm, size/S

#75 member_organizations: Fix order
  member_organizations.yaml
Labels: approved, lgtm, size/S

#73 Add note about keeping files alphabetized
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, size/XS

#76 Updating members and member_organizations
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, size/S

#79 Add inc0 to members
  members.yaml
Labels: approved, lgtm, size/XS

#81 Add Intel to member organisations
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#80 Adding Canonical
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#83 Add Michelle Casbon to members list
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, size/S

#84 Add Pachyderm to member organizations
  member_organizations.yaml
Labels: size/XS

#85 Adding Elson to member organization Intel.
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#86 add momenta into member org
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#87 Update member_organizations.yaml
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#88 Add wbuchwalter to members
  members.yaml
Labels: approved, lgtm, size/XS

#92 add Datawire
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#94 inserts MH9 into the correct position
  members.yaml
Labels: approved, lgtm, size/XS

#95 Tidy Red Hat's entry in the organization list.
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#96 Update members.yaml
  members.yaml
Labels: approved, lgtm, size/XS

#97 Add ankushagarwal to OWNERS and members
  OWNERS
  members.yaml
Labels: approved, lgtm, size/S

#98 Adding Heptio as an org
  member_organizations.yaml
Labels: approved, lgtm, size/S

#99 Add willingc to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#100 Add Project Jupyter to org list and myself to member list
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, size/S

#101 Add @ewilderj into members.yaml
  members.yaml
Labels: approved, lgtm, size/XS

#104 Add Huawei as member company
  member_organizations.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#91 Create a K8s app to deploy cncf/devstats for Kubeflow.
  devstats/Dockerfile.devstats
  devstats/Makefile
  devstats/README.md
  devstats/ks-app/.ksonnet/registries/incubator/40285d8a14f1ac5787e405e1023cf0c07f6aa28c.yaml
  devstats/ks-app/app.yaml
  devstats/ks-app/components/backfill.jsonnet
  devstats/ks-app/components/devstats-parts.libsonnet
  devstats/ks-app/components/devstats.jsonnet
  devstats/ks-app/components/params.libsonnet
  devstats/ks-app/components/projects.yaml
  devstats/ks-app/components/syncronjob.jsonnet
  devstats/ks-app/environments/base.libsonnet
  devstats/ks-app/environments/default/main.jsonnet
  devstats/ks-app/environments/default/params.libsonnet
  devstats/ks-app/lib/v1.7.0/k.libsonnet
  devstats/ks-app/lib/v1.7.0/k8s.libsonnet
  devstats/ks-app/lib/v1.7.0/swagger.json
  devstats/postgre-docker-entrypoint.sh
Labels: approved, lgtm, size/XXL

#105 A simple script to print the names of the companies.
  scripts/print_companies.py
Labels: approved, lgtm, size/S

#108 Add Seldon to member orgs
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, size/M

#111 Adding Microsoft Org
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#114 add Alibaba cloud in org list
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#112 Update member organization
  member_organizations.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#116 Add Uber to member organizations
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#117 Improve documentation about setting up a new repository
  repository-setup.md
Labels: approved, lgtm, size/M

#118 Fix typos and add new org Ant Financial
  member_organizations.yaml
Labels: approved, lgtm, size/S

#119 Update member_organizations.yaml
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#120 Update members.yaml
  members.yaml
Labels: approved, lgtm, size/XS

#107 Deploy grafana to show the dashboards
  devstats/README.md
  devstats/deploy-config/devstats.jinja
  devstats/deploy-config/devstats.yaml
  devstats/ks-app/components/devstats-parts.libsonnet
  devstats/ks-app/components/grafana/dashboards/activity-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/approvers-in-repository-groups-table.json
  devstats/ks-app/components/grafana/dashboards/approvers-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/blocked-prs-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/bot-commands-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/commenters-in-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/comments-in-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/commits-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/community-stats-repositories.json
  devstats/ks-app/components/grafana/dashboards/companies-contributing-in-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/companies-statistics-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/companies-table.json
  devstats/ks-app/components/grafana/dashboards/companies-velocity-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/dashboards.json
  devstats/ks-app/components/grafana/dashboards/developers-table.json
  devstats/ks-app/components/grafana/dashboards/first-non-author-activity-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/issues-repository-group.json
  devstats/ks-app/components/grafana/dashboards/new-and-episodic-contributors-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/new-and-episodic-issues-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/new-prs-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/open-issues-prs-by-milestone-and-repository.json
  devstats/ks-app/components/grafana/dashboards/opened-to-merged-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/pr-comments.json
  devstats/ks-app/components/grafana/dashboards/project-statistics-table.json
  devstats/ks-app/components/grafana/dashboards/prs-age-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/prs-approval-repository-groups-stacked.json
  devstats/ks-app/components/grafana/dashboards/prs-approval-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/prs-authors-companies-table.json
  devstats/ks-app/components/grafana/dashboards/prs-authors-repository-groups-table.json
  devstats/ks-app/components/grafana/dashboards/prs-authors-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/prs-labels-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/prs-merged-repos.json
  devstats/ks-app/components/grafana/dashboards/prs-merged-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/reviewers-in-repository-groups-table.json
  devstats/ks-app/components/grafana/dashboards/reviewers-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/suggested-approvers-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/time-metrics-by-repository-groups.json
  devstats/ks-app/components/grafana/dashboards/top-commenters-in-repository-groups-table.json
  devstats/ks-app/components/grafana/dashboards/user-reviews-repository-groups.json
  devstats/ks-app/components/grafana/providers.yaml
  devstats/modify_dashboards.sh
  devstats/print_imports.sh
  devstats/scripts/all/repo_groups.sql
Labels: approved, lgtm, size/XXL
