Repository kubeflow/community, pull requests merged in 2019-04, with the labels that each got.

#245 Add bloomberg to member org and dsun to members
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, ok-to-test, size/S

#252 add zabbasi to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#253 Add aws to org and member
  member_organizations.yaml
  members.yaml
Labels: approved, lgtm, ok-to-test, size/S

#251 Aggressively pruning the OWNERs file to better auto-assign reviewers.
  OWNERS
  scripts/OWNERS
Labels: approved, lgtm, size/S

#255 Create issue_label_bot.yaml
  .github/issue_label_bot.yaml
Labels: approved, lgtm, size/XS

#249 Fix project_stats; properly compute closed time.
  scripts/project_stats.ipynb
  scripts/project_stats.py
Labels: approved, lgtm, size/XXL

#257 Add jingzhang36 to kubeflow community.
  members.yaml
Labels: approved, lgtm, size/XS

#258 Delete members.yaml
  members.yaml
Labels: approved, lgtm, size/L

#259 Add myself to Ant Financial
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#260 Added LinkedIn to member organizations
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#262 Add jian-he to the org list
  member_organizations.yaml
Labels: approved, lgtm, size/XS
