Repository kubeflow/community, pull requests merged in 2019-05, with the labels that each got.

#263 Move PVC template design from tf-operator to community repo
  proposals/pvc-template.md
Labels: approved, lgtm, size/L

#261 Add Wei Yan(@ywskycn) to ant fin team
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#265 add iguazio
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#266 Create a notebook to compute github stats using BigQuery.
  devstats/ks-app/components/devstats-parts.libsonnet
  devstats/ks-app/components/params.libsonnet
  scripts/github_stats.ipynb
  scripts/print_companies.py
  scripts/project_stats.ipynb
Labels: approved, lgtm, size/XXL

#268 Adding instructions for reinit script
  devstats/README.md
  devstats/config/devel/restore_db.sh
Labels: approved, lgtm, size/M
