Repository kubeflow/community, pull requests merged in 2019-11, with the labels that each got.

#296 Labels and owners list
  labels-owners.yaml
  proposals/issue_triage.md
Labels: approved, lgtm, size/L

#297 Add a plot about new issues last 28 days.
  scripts/github_stats.ipynb
Labels: approved, lgtm, size/XXL

#298 Update calendar_import script and add kubecon events.
  calendar.yaml
  scripts/calendar_import.py
Labels: approved, lgtm, size/L

#299 Updates On Premise WG schedule to bi-weekly
  calendar.yaml
Labels: approved, lgtm, size/XS

#300 add jinchihe in IBM contacts
  member_organizations.yaml
Labels: approved, lgtm, size/XS

#302 Add Gojek to member_organizations
  member_organizations.yaml
Labels: approved, lgtm, size/S

#301 Update calendar.yaml to add the book signing
  calendar.yaml
Labels: approved, cla: yes, lgtm, size/S

#303 Fix the calendar community events
  calendar.yaml
Labels: approved, cla: yes, lgtm, size/XS
