Repository kubeflow/community, pull requests merged in 2019-08, with the labels that each got.

#281 Proposal for triaging GitHub issues
  proposals/issue_triage.md
Labels: approved, lgtm, size/M

#284 Compute statistics related to the release.
  scripts/github_stats.ipynb
  scripts/project_stats.ipynb
Labels: approved, lgtm, size/XXL

#283 Put calendar events in code
  calendar.yaml
  scripts/calendar_import.py
Labels: approved, lgtm, size/L

#287 Updating issue bot configs
  .github/issue_label_bot.yaml
Labels: approved, lgtm, size/XS
