Repository kubeflow/community, pull requests merged in 2020-10, with the labels that each got.

#417 Don't allow a sig to own subprojects
  generator/app.go
  wg-list.md
  wg-pipelines/README.md
  wgs.yaml
Labels: approved, cla: yes, lgtm, size/S

#418 Don't referece kubernetes in templates
  generator/sig_readme.tmpl
  generator/ug_readme.tmpl
Labels: approved, cla: yes, lgtm, size/S

#407 Add WG Notebooks
  OWNERS_ALIASES
  wg-list.md
  wg-notebooks/README.md
  wg-notebooks/charter.md
  wgs.yaml
Labels: approved, cla: yes, lgtm, size/L

#423 chore: update KFP community meeting video link
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/XS

#419 Add Feature Store SIG meetup to calendar
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/S

#428 Automatically sync the calendar
  calendar/Dockerfile
  calendar/Makefile
  calendar/README.md
  calendar/calendar_import.py
  calendar/latest_image.yaml
  calendar/manifests/deployment.yaml
  calendar/manifests/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#422 Add sig-onprem
  slack/slack_channels.md
Labels: approved, cla: yes, lgtm, size/XS

#431 calendar_import.py should use OAuth credentials for autobot@kubeflow.org
  calendar/Dockerfile
  calendar/Makefile
  calendar/README.md
  calendar/calendar_import.py
  calendar/latest_image.yaml
  calendar/manifests/deployment.yaml
  calendar/manifests/kustomization.yaml
  calendar/manifests/service-account.yaml
Labels: approved, cla: yes, lgtm, size/L

#432 changed kf 8AM pst meeting id to kf030
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/XS
