Repository kubeflow/community, pull requests merged in 2020-09, with the labels that each got.

#410 Update proposal-workflow.md
  proposal-workflow.md
Labels: approved, cla: yes, lgtm, size/XS

#388 Update Red Hat contacts
  member_organizations.yaml
Labels: approved, cla: yes, lgtm, size/XS

#412 fix(calendar): fixed Kubeflow community call (US East/EMEA)
  calendar/README.md
  calendar/calendar.yaml
  scripts/calendar_import.py
Labels: approved, cla: yes, lgtm, size/S

#408 Add a Feature Store SIG
  OWNERS_ALIASES
  sig-feature-store/README.md
  sig-feature-store/charter.md
  wgs.yaml
Labels: approved, cla: yes, lgtm, size/L

#395 Adding ML Pipelines WG charter
  OWNERS_ALIASES
  wg-list.md
  wg-pipelines/README.md
  wgs.yaml
  wgs/wg-pipelines/wg-charter-pipelines.md
Labels: approved, cla: yes, do-not-merge/invalid-owners-file, lgtm, size/L

#414 Add additional members to Kubeflow org on Docker Hub
  how-to/kubeflow_assets.md
Labels: approved, cla: yes, lgtm, size/XS
