Repository kubeflow/community, pull requests merged in 2020-11, with the labels that each got.

#443 Create a fake test meeting to debug #438.
  calendar/calendar.yaml
  calendar/calendar_import.py
Labels: approved, cla: yes, lgtm

#444 Bump the calendar id for the community meeting to see if that fixes the invite
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/XS

#436 wg-notebooks: Update scope
  OWNERS_ALIASES
  wg-list.md
  wg-notebooks/README.md
  wg-notebooks/charter.md
  wgs.yaml
Labels: approved, cla: yes, lgtm, size/S

#435 wg-manifests: Introduce WG Manifests
  OWNERS_ALIASES
  sig-feature-store/README.md
  sig-feature-store/charter.md
  wg-automl/charter.md
  wg-list.md
  wg-manifests/README.md
  wg-manifests/charter.md
  wg-notebooks/charter.md
  wgs.yaml
Labels: approved, cla: yes, lgtm, size/L

#402 create wg-deployment
  OWNERS_ALIASES
  wg-deployment/README.md
  wg-deployment/charter.md
  wg-list.md
  wgs.yaml
Labels: approved, cla: yes, lgtm, size/L

#434 Proposal future ownership/development of Kubeflow distributions should be outside Kubeflow
  proposals/kubeflow-distributions.md
Labels: approved, cla: yes, lgtm, size/M

#441 Add a slack channel for wg-notebooks
  slack/slack_channels.md
Labels: approved, cla: yes, lgtm, size/XS

#447 Small fixes in wg-manifests, wg-notebooks
  OWNERS_ALIASES
  wg-deployment/README.md
  wg-list.md
  wgs.yaml
  wgs/wg-pipelines/wg-charter-pipelines.md
Labels: approved, cla: yes, lgtm, size/L

#448 Add wg-manifests and wg-deployment slack channels
  slack/slack_channels.md
Labels: approved, cla: yes, lgtm, size/XS

#452 Change AutoML meeting ID
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/S

#453 Fix calendar for Feature Store SIG
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/XS

#457 removed on-prem meeting
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/S

#458 Update OWNERS, remove karlschriek
  calendar/OWNERS
Labels: approved, cla: yes, lgtm, size/XS
