Repository kubeflow/community, pull requests merged in 2020-07, with the labels that each got.

#351 #350 fixed
  .gitignore
  calendar.yaml
Labels: approved, cla: yes, lgtm, size/XS

#352 Update calendar.yaml
  calendar.yaml
Labels: approved, cla: yes, lgtm, size/XS

#353 Added Slack Guidelines
  slack/OWNERS
  slack/README.md
  slack/slack_channels.md
Labels: approved, cla: yes, lgtm, size/L

#348 Proposal for Kubeflow WG Guidelines/Governance
  proposals/wgs/community-membership.md
  proposals/wgs/overview.md
  proposals/wgs/templates/wg-charter-template.md
  proposals/wgs/templates/wgs.yaml
  proposals/wgs/wg-charter.md
  proposals/wgs/wg-governance-requirements.md
  proposals/wgs/wg-governance.md
  proposals/wgs/wg-lifecycle.md
Labels: approved, cla: yes, lgtm, size/XL

#365 Calendar cleanup
  calendar.yaml
  scripts/calendar_import.py
Labels: approved, cla: yes, lgtm, size/L

#371 Fixing cross doc links
  proposals/wgs/wg-charter.md
Labels: approved, cla: yes, lgtm, size/S

#370 Add KFP community meeting to KF calendar
  calendar.yaml
Labels: approved, cla: yes, lgtm, size/M

#355 Move the altair import to the top of the notebook
  scripts/github_stats.ipynb
Labels: approved, cla: yes, lgtm, size/XXL

#374 Change On-Premis meeting to weekly and updated URL
  calendar.yaml
Labels: approved, cla: yes, lgtm, size/XS

#373 WGs housecleaning
  wgs/OWNERS_ALIASES
  wgs/community-membership.md
  wgs/overview.md
  wgs/templates/wg-charter-template.md
  wgs/wg-charter.md
  wgs/wg-foo/OWNERS
  wgs/wg-governance-requirements.md
  wgs/wg-governance.md
  wgs/wg-lifecycle.md
  wgs/wgs.yaml
Labels: approved, cla: yes, lgtm, size/M

#376 Update member_organizations.yaml
  member_organizations.yaml
Labels: approved, cla: yes, lgtm, size/XS
