Repository kubeflow/community, pull requests merged in 2020-06, with the labels that each got.

#334 Add guideline on authentication and authorization
  guidelines/auth.md
  guidelines/images/kubeflow_request_flow.svg
Labels: approved, cla: yes, lgtm, size/L

#339 Document the different assets that power kubeflow.org and their owners.
  how-to/kubeflow_assets.md
Labels: approved, cla: yes, lgtm, size/L

#335 Add fate-operator proposal.
  proposals/diagrams/fate-operator-1.png
  proposals/diagrams/fate-operator-2.png
  proposals/diagrams/fate-operator-3.png
  proposals/diagrams/fate-operator-fl.png
  proposals/diagrams/fate-operator-overall.png
  proposals/fate-operator-proposal.md
Labels: approved, cla: yes, lgtm, size/L

#343 Added recurring Model Management SIG Call
  calendar.yaml
Labels: approved, cla: yes, lgtm, size/S

#346 Add D2iQ to member orgs
  member_organizations.yaml
Labels: approved, cla: yes, lgtm, size/XS

#347 fix(fate-operator): Fix the egg replicas
  proposals/fate-operator-proposal.md
Labels: approved, cla: yes, lgtm, size/XS

#349 Rename Ant Financial to Ant Group
  member_organizations.yaml
Labels: approved, cla: yes, lgtm, size/XS
