Repository kubeflow/community, pull requests merged in 2020-08, with the labels that each got.

#356 feat(wg): Add WG Training
  .gitignore
  proposals/wgs/training/wg-charter-training.md
  proposals/wgs/training/wgs.yaml
Labels: approved, cla: yes, lgtm, size/L

#382 changed Tuesday 8:00AM (id kf002) community call URL
  calendar.yaml
Labels: approved, cla: yes, lgtm, size/S

#383 Move WG Training to the correct location
  wgs/wg-training/wg-charter-training.md
  wgs/wg-training/wgs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#357 Moved calendar.yaml to calendar/calendar.yaml
  calendar/OWNERS
  calendar/calendar.yaml
  scripts/calendar_import.py
Labels: approved, cla: yes, lgtm, size/S

#384 Remove KFP community meeting from calendar.
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/M

#385 Add pipelines team members as root OWNER
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#386 Temporarily disable KFP community meeting invite
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/S

#387 Added an new frequency option for "every 4 weeks"
  scripts/calendar_import.py
Labels: approved, cla: yes, lgtm, size/XS

#389 Update KFP community call to every-4-weeks
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/S

#358 Add WG AutoML
  wgs/wg-automl/charter.md
  wgs/wg-automl/wgs.yaml
Labels: approved, cla: yes, lgtm, size/M

#391 Update community calendar invite
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/S

#392 feat: Update caicloud team
  member_organizations.yaml
Labels: approved, cla: yes, lgtm, size/S

#394 Add AutoML WG Slack channel
  slack/slack_channels.md
Labels: approved, cla: yes, lgtm, size/XS

#393 Add WG Serving
  wgs/wg-serving/wg-charter-serving.md
  wgs/wg-serving/wgs.yaml
Labels: approved, cla: yes, lgtm, size/L

#354 Update Canonical in member_organizations.yaml
  member_organizations.yaml
Labels: approved, cla: yes, lgtm, size/XS

#401 Copy over autogenerate tool from k8s/community
  Makefile
  OWNERS_ALIASES
  generator/README.md
  generator/aliases.tmpl
  generator/app.go
  generator/header.tmpl
  generator/list.tmpl
  generator/sig_readme.tmpl
  generator/ug_readme.tmpl
  generator/wg_readme.tmpl
  go.mod
  go.sum
  wg-automl/README.md
  wg-automl/charter.md
  wg-list.md
  wg-serving/README.md
  wg-serving/charter.md
  wg-training/README.md
  wg-training/charter.md
  wgs.yaml
  wgs/OWNERS_ALIASES
  wgs/wg-automl/wgs.yaml
  wgs/wg-lifecycle.md
  wgs/wg-serving/wgs.yaml
  wgs/wg-training/wgs.yaml
  wgs/wgs.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#396 Add AutoML meeting to calendar
  calendar/calendar.yaml
  scripts/calendar_import.py
  wg-automl/README.md
  wg-list.md
  wgs.yaml
Labels: approved, cla: yes, lgtm, size/M

#404 Add calendar update instruction
  calendar/README.md
Labels: approved, cla: yes, lgtm, size/S

#405 add calendar_import.py requirements
  scripts/requirements.txt
Labels: approved, cla: yes, lgtm, size/XS

#406 calendar_sync.py setup instructions
  calendar/README.md
  scripts/requirements.txt
Labels: approved, cla: yes, lgtm, size/S
