Repository kubeflow/community, pull requests merged in 2020-05, with the labels that each got.

#332 Updated label owners and info about shared drive
  how-to/sharing_docs.md
  labels-owners.yaml
Labels: approved, cla: yes, lgtm, size/XS

#311 label-owners: Add Arrikto folk to relevant labels
  labels-owners.yaml
Labels: approved, cla: yes, lgtm, size/S

#330 Add missing starting parenthesis
  devstats/README.md
Labels: approved, cla: yes, lgtm, size/XS

#333 Fix YAML syntax areas in labels-owners file.
  labels-owners.yaml
Labels: approved, cla: yes, lgtm, size/XS

#337 Document how we administer the GitHub org.
  how-to/github_admin.md
  repository-setup.md
Labels: approved, cla: yes, lgtm, size/M
