Repository kubeflow/community, pull requests merged in 2021-01, with the labels that each got.

#467 Update AutoML WG GitHub team
  wg-automl/README.md
  wgs.yaml
Labels: approved, cla: yes, lgtm, size/S

#468 Add member organization: AInnovation
  member_organizations.yaml
Labels: approved, cla: yes, lgtm, size/S

#469 Remove AutoML meetings from the Kubeflow calendar
  calendar/calendar.yaml
Labels: approved, cla: yes, lgtm, size/M

#471 Fix broken link in wg-lifecycle.md
  wgs/wg-lifecycle.md
Labels: approved, cla: yes, size/XS
