Repository kubeflow/community, pull requests merged in 2021-11, with the labels that each got.

#528 Some editorial changes to KF conformance RFC.
  proposals/kubeflow-conformance-program-proposal.md
Labels: size/S, lgtm, approved, cla: yes

#536 Add release related documentation (#531)
  releases/OWNERS
  releases/README.md
  releases/handbook.md
  releases/release-1.4/README.md
  releases/release-1.4/release-team.md
  releases/release-1.5/README.md
  releases/release-1.5/release-team.md
  releases/retrospectives/release-1.3.md
  releases/retrospectives/release-1.4.md
Labels: lgtm, approved, size/XL, cla: yes

#539 retro-1.4: Add links to the recordings
  releases/retrospectives/release-1.4.md
Labels: size/S, lgtm, approved, cla: yes

#541 Update handbook.md
  releases/handbook.md
Labels: lgtm, size/XS, approved, cla: yes
