Repository kubeflow/community, pull requests merged in 2023-06, with the labels that each got.

#633 fix(pipelines): Update KFP organizer list
  wg-pipelines/README.md
Labels: lgtm, size/XS, approved

#634 Add Notebooks WG to community calendar
  .gitignore
  calendar/.calendar.yaml.swp
  calendar/calendar.yaml
Labels: size/S, lgtm, approved

#632 manifests: Update charter for leadership roles
  wg-manifests/charter.md
Labels: lgtm, approved, size/M
