Repository kubeflow/community, pull requests merged in 2023-12, with the labels that each got.

#665 KSC Election Process Proposal.md
  elections/kubeflow-steering-committee-elections-2023.md
  proposals/kubeflow-steering-committee-election-proposal.md
Labels: lgtm, size/XS, approved

#658 Adopt CNCF's Code of Conduct
  CODE_OF_CONDUCT.md
Labels: lgtm, size/M

#666 Update kubeflow-steering-committee-elections-2023.md
  elections/kubeflow-steering-committee-elections-2023.md
Labels: lgtm, approved, size/M

#667 Create eligible-candidates-and-voters-2023-ksc.md
  elections/eligible-candidates-and-voters-2023-KSC.md
Labels: size/L, lgtm, approved

#668 Update eligible-candidates-and-voters-2023-KSC.md
  elections/eligible-candidates-and-voters-2023-KSC.md
Labels: lgtm, size/XS, approved

#669 Update eligible-candidates-and-voters-2023-KSC.md
  elections/eligible-candidates-and-voters-2023-KSC.md
Labels: lgtm, size/XS, approved

#671 Security Team Meeting Update calendar.yaml
  calendar/calendar.yaml
Labels: lgtm, size/XS, approved
