Repository kubeflow/community, pull requests merged in 2023-09, with the labels that each got.

#647 change Community Meeting to weekly
  calendar/calendar.yaml
Labels: lgtm, size/XS, approved

#651 Update Security WG meeting calendar
  calendar/calendar.yaml
Labels: size/S, lgtm, approved

#652 Add AutoML and Training WG Meeting to Kubeflow Calendar
  calendar/calendar.yaml
Labels: lgtm, approved, size/M

#645 Add Kubeflow Steering Committee election proposal.
  proposals/kubeflow-steering-committee-election-proposal.md
Labels: size/L, lgtm, approved
