Repository kubeflow/community, pull requests merged in 2023-08, with the labels that each got.

#641 Update kfp community meeting organizer and cleanup attendees
  calendar/calendar.yaml
Labels: size/S, lgtm, approved

#639 clean up calendar and remove legacy meetings
  calendar/calendar.yaml
Labels: size/L, lgtm, approved

#642 add chensun to calendar OWNERS
  calendar/OWNERS
Labels: lgtm, size/XS, approved
