Repository kubeflow/community, pull requests merged in 2024-11, with the labels that each got.

#786 Proposal to allow 1 KSC seat per organization, starting from 2025 election.
  proposals/kubeflow-steering-committee-election-proposal.md
Labels: lgtm, size/XS, approved

#785 Introduce rule to allow 1 vote only from the same organization
  KUBEFLOW-STEERING-COMMITTEE.md
Labels: lgtm, size/XS, approved

#788 Create kubeflow-steering-committee-elections-2024.md
  elections/eligible-candidates-and-voters-2024-ksc.md
  elections/kubeflow-steering-committee-elections-2024.md
Labels: size/L, lgtm, approved

#789 Change Pipelines WG meeting details
  calendar/calendar.yaml
Labels: lgtm, size/XS, approved

#790 Update eligible-candidates-and-voters-2024-ksc.md
  elections/eligible-candidates-and-voters-2024-ksc.md
Labels: lgtm, size/XS, approved

#793 Fix typos in eligible-candidates-and-voters-2023-KSC.md
  elections/eligible-candidates-and-voters-2023-ksc.md
Labels: lgtm, size/XS
