Repository kubeflow/community, pull requests merged in 2024-07, with the labels that each got.

#725 Merge security and manifests WG meeting in a cal entry
  calendar/calendar.yaml
Labels: lgtm, approved, size/M

#729 Move legacy release-team file
  releases/release-1.8/release-team.md
Labels: lgtm, size/XS, approved

#724 Update Kubeflow 1.9 schedule
  releases/release-1.9/README.md
Labels: size/S, lgtm, approved

#731 Move the Pipelines WG PST PM meeting to PST AM
  calendar/calendar.yaml
Labels: lgtm, approved, size/M
