Repository kubeflow/community, pull requests merged in 2024-02, with the labels that each got.

#690 Add 1.9 Release Schedule Timeline
  releases/release-1.9/README.md
Labels: lgtm, approved, size/M

#696 add calendar for Model Registry community call
  calendar/calendar.yaml
Labels: size/S, lgtm, approved

#699 Add KSC members to approvers in OWNERS
  OWNERS
Labels: lgtm, size/XS, approved

#700 move Model Registry meeting on Mondays
  calendar/calendar.yaml
Labels: lgtm, size/XS, approved

#702 Initialize KSC folder and document key decisions
  ksc/README.md
  ksc/decision-log.md
Labels: lgtm, approved, size/M

#650 Add KSC charter
  proposals/kubeflow-steering-committee-charter.md
Labels: size/L, lgtm, approved

#704 Change AutoML and Training WG call to 2pm UTC
  calendar/calendar.yaml
Labels: size/S, lgtm, approved

#703 Added DCO sign-off hook and updated info regarding the migration from CLA to DCO
  CONTRIBUTING.md
  dco-signoff-hook/README.md
  dco-signoff-hook/prepare-commit-msg
Labels: lgtm, approved, size/M
