Repository kubeflow/community, pull requests merged in 2025-07, with the labels that each got.

#842 Proposal Release Updates
  proposals/841-release-process/README.md
  proposals/841-release-process/release.png
  releases/handbook.md
Labels: size/L, lgtm, approved

#870 Update calendar.yaml
  calendar/calendar.yaml
Labels: lgtm, size/XS, approved

#866 add Social Media Lead to the Kubeflow Outreach Committee
  KUBEFLOW-OUTREACH-COMMITTEE.md
Labels: lgtm, size/XS, approved

#875 Update kfp maintainers
  wgs.yaml
Labels: lgtm, approved, size/M

#869 KEP-867: Kubeflow Documentation AI Assistant with Retrieval-Augmented Generation
  proposals/867-kubeflow-documentation-ai/README.md
  proposals/867-kubeflow-documentation-ai/assets/indexing.svg
  proposals/867-kubeflow-documentation-ai/assets/query.svg
Labels: lgtm, approved, size/XL

#877 Update teams to match acls repo
  KUBEFLOW-OUTREACH-COMMITTEE.md
  wg-pipelines/README.md
  wgs.yaml
Labels: size/S, lgtm, approved
