Repository kubeflow/community, pull requests merged in 2025-02, with the labels that each got.

#813 Updating OWNERS for 2025 KSC members
  OWNERS
Labels: size/XS, approved

#806 Explain how to Transfer Ownership for KSC Members
  KUBEFLOW-STEERING-COMMITTEE.md
Labels: lgtm, approved, size/M

#814 Adding emeritus_approvers
  OWNERS
Labels: lgtm, size/XS, approved

#805 Add KEP template to be used by wider Kubeflow community
  proposals/NNNN-template/README.md
Labels: size/L, lgtm, approved

#816 chore: add trademark disclaimer
  README.md
Labels: lgtm, size/XS, approved
