Repository kubeflow/community, pull requests merged in 2025-04, with the labels that each got.

#844 Add CERN to ADOPTERS.md
  ADOPTERS.md
Labels: lgtm, size/XS, approved

#845 Update ADOPTERS with links for each project
  ADOPTERS.md
Labels: lgtm, approved, size/M

#846 Add Kubeflow CNCF Graduation Call
  calendar/calendar.yaml
Labels: size/S, lgtm, approved

#823 KEP-819: Kubeflow SDK for ML Experience
  proposals/819-kubeflow-sdk/README.md
  proposals/819-kubeflow-sdk/kubeflow-sdk.drawio.svg
Labels: size/L, lgtm, approved

#840 feat: Proposal for Kubeflow Outreach Committee
  KUBEFLOW-OUTREACH-COMMITTEE.md
  proposals/748-expand-kubeflow-ecosystem/README.md
  proposals/839-outreach-committee/README.md
Labels: size/L, lgtm, approved
